[package]
repository = "https://github.com/clog-tool/clog-cli"
readme = "README.md"
keywords = ["git", "log", "changelog", "parser", "parse"]
license = "MIT"
name = "clog-cli"
version = "0.9.1"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]
description = "A conventional changelog for the rest of us"
exclude = ["docs/*"]

[[bin]]
name = "clog"

[dependencies]
semver = "~0.2.3"
clap = "~2.2"
time = "~0.1.32"
clog = "~0.9.1"

[dependencies.ansi_term]
version = "~0.7.2"
optional = true

[features]
default = ["color"]

color = ["ansi_term"]

# For debugging output
debug = []

unstable = []
