[package]
repository = "https://github.com/clog-tool/clog-cli"
readme = "README.md"
keywords = ["git", "log", "changelog", "parser", "parse"]
license = "MIT"
name = "clog-cli"
version = "0.9.1"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]
description = "A conventional changelog for the rest of us"
exclude = ["docs/*"]

[[bin]]
name = "clog"

[dependencies]
semver = "~0.1.20"
clap = "~1.4"
time = "~0.1.32"
clog = "~0.9.0"

[dependencies.regex_macros]
version = "~0.1.21"
optional = true

[dependencies.ansi_term]
version = "~0.6.3"
optional = true

[features]
default = ["color"]

color = ["ansi_term"]

# For debugging output
debug = []

# for building with nightly and unstable features
# until regex_macros compiles with nightly again, this should be commented out
# unstable = ["regex_macros"]
unstable = []
