[package]
repository = "https://github.com/clog-tool/clog-cli"
readme = "README.md"
keywords = ["git", "log", "changelog", "parser", "parse"]
license = "MIT"
name = "clog-cli"
version = "0.8.2"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]
description = "A conventional changelog for the rest of us"
exclude = ["docs/*"]

[[bin]]
name = "clog"

[dependencies]
semver = "*"
clap = "*"
time = "*"
clog = {git = "https://github.com/clog-tool/clog-lib"}

[dependencies.regex_macros]
version = "*"
optional = true

[dependencies.ansi_term]
version = "*"
optional = true

[features]
default = ["color"]

color = ["ansi_term"]

# For debugging output
debug = []

# for building with nightly and unstable features
# until regex_macros compiles with nightly again, this should be commented out
# unstable = ["regex_macros"]
unstable = []
