[package]

name = "clog"
version = "0.2.0"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]

[dependencies.docopt]
git = "https://github.com/cburgdorf/docopt.rs"

[dependencies.docopt_macros]
git = "https://github.com/cburgdorf/docopt.rs"
