[package]

repository = "https://github.com/thoughtram/clog"
readme = "README.md"
keywords = ["git", "log", "changelog", "parser", "parse"]
license = "MIT"
name = "clog"
version = "0.7.0"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]
description = "A conventional changelog for the rest of us"

[dependencies]
regex = "*"
time = "*"
clap = "*"
semver = "*"
toml = "*"

[dependencies.regex_macros]
optional = true

[features]
default=[]
debug=[]

# for building with nightly and unstable features
# until regex_macros compiles with nightly again, this should be commented out
# unstable = ["regex_macros"]
unstable=[]
