[package]

repository = "https://github.com/thoughtram/clog"
readme = "README.md"
keywords = ["git", "log", "changelog", "parser", "parse"]
license = "MIT"
name = "clog"
version = "0.6.0"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]
description = "A conventional changelog for the rest of us"

[dependencies]
regex = "*"
time = "*"
clap = "*"
semver = "*"
toml = "*"

[dependencies.regex_macros]
optional = true

[features]
default=[]

# for building with nightly and unstable features
unstable=["regex_macros"]
